server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_db?currentSchema=db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


auth-server:
  name: dev


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761