server:
  port: 7000

spring:
  datasource:
    url: jdbc:postgresql://ecs-deployment-db.c2kfui9bmsnq.us-east-1.rds.amazonaws.com:5432/ecsdeploymentdb
    username: ecsdeploymentdb
    password: ecs-deployment-db
    driver-class-name: org.postgresql.Driver


user-onboarding-service:
  name: dev


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761